require 'unirest'

namespace :movies do
  desc "Get the movies from Netflix"
  task retrieve_movies: :environment do
    puts ENV['MOVIES_HOST']
    puts ENV['MOVIES_API_KEY']
    # response = Unirest.get "https://unogs-unogs-v1.p.rapidapi.com/aaapi.cgi?q=get:new7:CO&p=1&t=ns&st=adv",
    # headers:{
    #   "X-RapidAPI-Host" => ENV['MOVIES_HOST'],
    #   "X-RapidAPI-Key" => ENV['MOVIES_API_KEY']
    # }
    # puts response.body # Parsed body
    # puts response.raw_body # Unparsed body
    [
          {
              "netflixid": "70185023",
              "title": "Shor In the City",
              "image": "https://occ-0-3451-3446.1.nflxso.net/art/41915/d4cafe610713311d14cf0120789a7a2e6a641915.jpg",
              "synopsis": "When three small-time Mumbai crooks steal a bag on a train, they find that it&#39;s filled with weapons and realize that their lives may be in danger.<br><b>New on 2019-05-30</b>",
              "rating": "7.3",
              "type": "movie",
              "released": "2011",
              "runtime": "1h46m",
              "largeimage": "http://cdn1.nflximg.net/images/3477/24433477.jpg",
              "unogsdate": "2019-05-30",
              "imdbid": "tt1916728",
              "download": "1"
          },
          {
              "netflixid": "81010699",
              "title": "Svaha: The Sixth Finger",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABYNqIb7TZlQdIifLeuP9dn1h4kSEvU1ESRW7oZBEalQGSqcGbrtJO40a1ZqILHh8tHGTIDAMse5pplZ_uwkl2tv1vNtTkgHCPXUamU7mA_GBowuQvw.jpg?r=3bc",
              "synopsis": "A minister who researches religious cults turns to his Buddhist monk friend for help investigating a new group with mysterious origins.<br><b>New on 2019-05-30</b>",
              "rating": "",
              "type": "movie",
              "released": "2019",
              "runtime": "2h3m",
              "largeimage": "",
              "unogsdate": "2019-05-30",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "70202150",
              "title": "My Week with Marilyn",
              "image": "http://occ-0-299-1007.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABfOFe5FfrWUy-w2M-WhnHangxi00zBEIgLw85oAuyc6ochCt9a_MuqHZDwY6gLcOjk7zxxgl4ZIzqDAniB9xKGBXL0xP4JU.jpg?r=f6f",
              "synopsis": "While filming a movie in England, Hollywood icon Marilyn Monroe slips away with a young Brit for a week of self-discovery and frivolity.<br><b>New on 2019-05-30</b>",
              "rating": "7",
              "type": "movie",
              "released": "2011",
              "runtime": "1h38m",
              "largeimage": "http://cdn1.nflximg.net/images/5172/8495172.jpg",
              "unogsdate": "2019-05-30",
              "imdbid": "tt1655420",
              "download": "1"
          },
          {
              "netflixid": "70045644",
              "title": "Koi Aap Sa",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABUw5450BZgiKd6WzBKCQxv-BgXT1poyGge4dbQCtqvwAZGTC8dhSo8F0x1bBbDma5ZCH5eYqwyjj-wV8zz4tZnBerS8Ab9M.jpg?r=728",
              "synopsis": "Star athlete Rohan has his eye on a beautiful art student. But when his best friend Simran experiences a crisis, he drops everything to help her.<br><b>New on 2019-05-30</b>",
              "rating": "5.6",
              "type": "movie",
              "released": "2006",
              "runtime": "2h15m",
              "largeimage": "http://cdn1.nflximg.net/images/7207/24427207.jpg",
              "unogsdate": "2019-05-30",
              "imdbid": "tt0488840",
              "download": "1"
          },
          {
              "netflixid": "80993095",
              "title": "Chopsticks",
              "image": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABVKroBGzB3m-JjfrCCaL9e9U8NqziAN_ephdm52TcrH-gkdU3Yjl1qliuyceVTrWd4AhPEEih-Cvj82hhKMhS2edwCFfZ9VoLGOi3B88DDTbV-RpEg.jpg?r=f8e",
              "synopsis": "A gifted but insecure woman embarks on a transformative journey when she enlists an enigmatic con man to recover her stolen car from an eccentric thug.<br><b>New on 2019-05-31</b>",
              "rating": "0",
              "type": "movie",
              "released": "2019",
              "runtime": "1h40m",
              "largeimage": "",
              "unogsdate": "2019-05-31",
              "imdbid": "tt10243678",
              "download": "0"
          },
          {
              "netflixid": "80202874",
              "title": "Always Be My Maybe",
              "image": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABUNSBrjzn7Hn6ZFoKvyJEA2q0qxuAo9QiVxZuYh_lz4tyg4kXCk7wwRyFCGDYWNXVssi_oZ5VGJvTBhrGPkK1uIowUV-BFdYqERl8aj0GGYmIVBx6g.jpg?r=54f",
              "synopsis": "Reunited after 15 years, famous chef Sasha and hometown musician Marcus feel the old sparks of attraction but struggle to adapt to each other&#39;s worlds.<br><b>New on 2019-05-31</b>",
              "rating": "0",
              "type": "movie",
              "released": "2019",
              "runtime": "1h42m",
              "largeimage": "",
              "unogsdate": "2019-05-31",
              "imdbid": "tt7374948",
              "download": "0"
          },
          {
              "netflixid": "80083930",
              "title": "Ragini MMS",
              "image": "https://occ-0-3451-3446.1.nflxso.net/art/11bfd/f142ab0d46c3ffd72e4dae44112f81d01f511bfd.jpg",
              "synopsis": "A couple out to have a sensuous weekend at a house outside of Mumbai finds it rigged with surveillance cameras and occupied by an evil entity.<br><b>New on 2019-05-31</b>",
              "rating": "5",
              "type": "movie",
              "released": "2011",
              "runtime": "1h33m",
              "largeimage": "http://cdn0.nflximg.net/images/1626/24431626.jpg",
              "unogsdate": "2019-05-31",
              "imdbid": "tt1890513",
              "download": "1"
          },
          {
              "netflixid": "81111849",
              "title": "Pegasus",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAUiIrFjIQAJheF4nkrrOxDROo5rp6zWuY4M2msoAtlsNkUQ0X3WKyG_L_uL0mykrQoLtreu0TCLDoLe8z5Gntg2jTWC29eA.jpg?r=4ef",
              "synopsis": "After a five-year suspension, a once-legendary race car driver decides to get back in the game against a new generation of opponents.<br><b>New on 2019-05-31</b>",
              "rating": "6.4",
              "type": "movie",
              "released": "2019",
              "runtime": "1h38m",
              "largeimage": "",
              "unogsdate": "2019-05-31",
              "imdbid": "tt9597190",
              "download": "0"
          },
          {
              "netflixid": "80160033",
              "title": "P",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABUDcQWowcp0bIQyEzEV_X5n3U8Tlck-NxmBrsbDSiZ12DFXXcmvjuj0U7d-QgMK18IVeE_My6fvrB5fu7q8CAaLmGt2MPWg.jpg?r=715",
              "synopsis": "An orphan girl taught magic by her sick grandma must find work in seedy Bangkok, where unsavory characters run afoul of her increasingly dark powers.<br><b>New on 2019-05-31</b>",
              "rating": "5.1",
              "type": "movie",
              "released": "2006",
              "runtime": "1h44m",
              "largeimage": "",
              "unogsdate": "2019-05-31",
              "imdbid": "tt0449629",
              "download": "0"
          },
          {
              "netflixid": "80217946",
              "title": "Killer Ratings",
              "image": "https://occ-0-64-58.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABUeQ1FVNXyw5TR7KuUop_FpgUopqvl-xNpFPp8J53Qqqk2cbf_ZsI0ACO4kE9JVmlsiKvdGqyLK8s-GVmJ2okUd3ewPdD3MLawtbZFH2LS4IhMgKHA.jpg?r=530",
              "synopsis": "Brazilian TV personality and politician Wallace Souza faces accusations of masterminding the violent crimes he reported on and rallied against.<br><b>New on 2019-05-31</b>",
              "rating": "",
              "type": "series",
              "released": "2019",
              "runtime": "",
              "largeimage": "",
              "unogsdate": "2019-05-31",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "80218448",
              "title": "How to Sell Drugs Online (Fast)",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABeuC4OYL0XF1EgCijeO18uRjxqWEu4dVh4aW-seNFGjFNxUdg0cN5Vfgt9KYwkKOJUk3SDaJ8kPszad1LCaHMdbbpWZfanQEwpbCCElLW4wHFX_qCg.jpg?r=9ed",
              "synopsis": "To win back his ex-girlfriend, a nerdy teen starts selling ecstasy online out of his bedroom -- and becomes one of Europe&#39;s biggest dealers.<br><b>New on 2019-05-31</b>",
              "rating": "0",
              "type": "series",
              "released": "2019",
              "runtime": "",
              "largeimage": "",
              "unogsdate": "2019-05-31",
              "imdbid": "tt9184994",
              "download": "0"
          },
          {
              "netflixid": "81079046",
              "title": "Black Spot",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABRLTEojvtV6vct7dGwUuR0Zin8pa2AM5jqkSSXdvIUSAOJK_tpUTSOnxH5j55jM7JymXlF8BybWxBGrpQJ78HznOEBQvxcxlVvJlKoCDfO7WxZyqGw.jpg?r=f45",
              "synopsis": "A police chief and an eccentric new prosecutor investigate a string of grisly crimes and eerie phenomena in an isolated town at the edge of a forest.<br><b>New on 2019-05-31</b>",
              "rating": "0",
              "type": "series",
              "released": "2019",
              "runtime": "",
              "largeimage": "",
              "unogsdate": "2019-05-31",
              "imdbid": "tt7997942",
              "download": "0"
          },
          {
              "netflixid": "80059465",
              "title": "Vis a vis",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABfmhH9K8-KlDZqhf_D28vJX35pkPWqlo5ETO7SSPNVTlNuj5eek4FtfBp43vCkl4_kbAesZJEkgApf1n5QjgY9rI-vC-sbxOVOl4zgtCl5ywD8YQNQ.jpg?r=23f",
              "synopsis": "Young Macarena must learn to navigate a harsh new world when she&#39;s sent to prison for embezzlement and tax evasion.<br><b>New on 2019-05-31</b>",
              "rating": "8.2",
              "type": "series",
              "released": "2015",
              "runtime": "",
              "largeimage": "http://cdn1.nflximg.net/images/5497/22405497.jpg",
              "unogsdate": "2019-05-31",
              "imdbid": "tt4524056",
              "download": "1"
          },
          {
              "netflixid": "80200549",
              "title": "When They See Us",
              "image": "https://occ-0-2433-2705.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABVxryL9E0mRrzjKciNo2EjA0iToD8UJKeFG8prthSzOUSdwKTRlB_h_So15xuQzbWCedz1ksXqWjz-6GMlPnudk_VrehnorI6FjGDDhi6LOt-GjrKQ.jpg?r=f01",
              "synopsis": "Five teens from Harlem become trapped in a nightmare when they&#39;re falsely accused of a brutal attack in Central Park. Based on the true story.<br><b>New on 2019-05-31</b>",
              "rating": "0",
              "type": "series",
              "released": "2019",
              "runtime": "",
              "largeimage": "",
              "unogsdate": "2019-05-31",
              "imdbid": "tt7137906",
              "download": "0"
          },
          {
              "netflixid": "80188935",
              "title": "A Thousand Goodnights",
              "image": "https://occ-0-2433-2705.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABVXrwb5LJ80SQVYb4vu6ThJ6wrEticHIP1qm3CVIBnGoI2D1JYe79hs3uu5A9e-NM6BpUZ-smQhEPwzyna86XvWQ9KZk7yQZ1q60L0UKhaH0S6uMPQ.jpg?r=e3e",
              "synopsis": "To carry out her dad&#39;s wish and discover her roots, Dai Tian-qing embarks on a journey around Taiwan and finds love and redemption on the way.<br><b>New on 2019-05-31</b>",
              "rating": "",
              "type": "series",
              "released": "2019",
              "runtime": "",
              "largeimage": "",
              "unogsdate": "2019-05-31",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "70025612",
              "title": "Krishna Cottage",
              "image": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAZbkg65ceBmZ-5KJyWefSC7OeM__XlAT6iwUI-UOXYXLD7r7CrfdQTRul40O3p43_AbXIyiDvivp65YrD6tKBCVB5vjAoPs.jpg?r=752",
              "synopsis": "True love is put to the test when another woman comes between a pair of star-crossed young lovers in this thriller.<br><b>New on 2019-05-31</b>",
              "rating": "5.1",
              "type": "movie",
              "released": "2004",
              "runtime": "2h3m",
              "largeimage": "",
              "unogsdate": "2019-05-31",
              "imdbid": "tt0408976",
              "download": "1"
          },
          {
              "netflixid": "81087094",
              "title": "Lifechanger",
              "image": "https://occ-0-32-34.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABT6diwj0A5eClVaSjjBqO3-wmjgTp-hx9CXvOVrkX6MpxKtPepPkecafFN0FQc01PYKYj5nlWcEYxHuyxl16CMP0Qf7NvPI.jpg?r=ad3",
              "synopsis": "A shapeshifter has to kill, then inhabit his victims, or die. But as his need for new bodies speeds up, he finally faces down his own mortality.<br><b>New on 2019-05-31</b>",
              "rating": "5.4",
              "type": "movie",
              "released": "2018",
              "runtime": "1h23m",
              "largeimage": "",
              "unogsdate": "2019-05-31",
              "imdbid": "tt7188978",
              "download": "0"
          },
          {
              "netflixid": "80237006",
              "title": "Mere Pyare Prime Minister",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABYhuMR6v8E_amaLWC31MK4L8adobew2SXUhQst7OWXkmlJaZeI2ecdPVxqh1iErS1HGGjlh9NeRfsw6ObimHvL500n0SDl0.jpg?r=d4c",
              "synopsis": "When his mother suffers a traumatic incident, a boy from the Mumbai slums treks to Delhi to deliver his written plea for justice to the Prime Minister.<br><b>New on 2019-05-31</b>",
              "rating": "7.6",
              "type": "movie",
              "released": "2018",
              "runtime": "1h43m",
              "largeimage": "",
              "unogsdate": "2019-05-31",
              "imdbid": "tt8207768",
              "download": "0"
          },
          {
              "netflixid": "81032375",
              "title": "Bullitt County",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAVzrd2qk1iIQXMRjUKRsJ-qMpPMrEAKGS11HHxqs0RSsGbWT2UA2eSJJ5L0oCUK1FhBcoIrFv0siyqmLUZWNRtHRSHsyOhs.jpg?r=e72",
              "synopsis": "When four college friends reunite for a bachelor party, their hunt for cash said to be hidden in Kentucky&#39;s backwoods leads to bloodshed and betrayal.<br><b>New on 2019-06-01</b>",
              "rating": "5",
              "type": "movie",
              "released": "2018",
              "runtime": "1h38m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "tt6140148",
              "download": "0"
          },
          {
              "netflixid": "60023855",
              "title": "Carmen: A Hip Hopera",
              "image": "http://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABSEmLrqF3SOW0m0nLIaAaZltEgWGQDyNejkVgMIRGaKUFcoQ7mV-EMcdhWlPV9gqhGeO0ej_I1ehDFVZrU7Fjgo2MknNy_g.jpg?r=d46",
              "synopsis": "Beyonc&eacute; Knowles and Mekhi Phifer star in Bizet&#39;s famed opera of passion, romance, betrayal and tragedy, retold hip-hop style. Knowles is the mesmerizing and irresistible Carmen, a temptress who&#39;s involved with Sgt.<br><b>New on 2019-06-01</b>",
              "rating": "4.8",
              "type": "movie",
              "released": "2001",
              "runtime": "1h25m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0274415",
              "download": "0"
          },
          {
              "netflixid": "70060018",
              "title": "10,000 B.C.",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAUr7schh6aAdQq9uHj4K-NkGsSSSIonf73Rfw3XV-1ulMcCqFtmCqbccY1kUh7mB4_aNJ9RKGS4RNhXPIvyJjaeBZdvN6jI.jpg?r=3e9",
              "synopsis": "Fierce mammoth hunter D&#39;Leh sets out on an impossible journey to rescue the woman he loves from a vicious warlord and save the people of his village.<br><b>New on 2019-06-01</b>",
              "rating": "5.1",
              "type": "movie",
              "released": "2008",
              "runtime": "1h49m",
              "largeimage": "http://cdn1.nflximg.net/images/8205/8098205.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0443649",
              "download": "0"
          },
          {
              "netflixid": "70105600",
              "title": "Gran Torino",
              "image": "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABTPcNRHJQwzjVKTTZGhKAYdSTKqDUqtB3L3yYffnYZLSZu9ACxnv3MWSLJBtzaHI3liwYGpcVtLaPcV-zVwlWbSm9tJgkrk.jpg?r=258",
              "synopsis": "Curmudgeonly Korean War vet Walt confronts his Hmong immigrant neighbors when the family&#39;s son tries to steal his beloved 1972 Gran Torino.<br><b>New on 2019-06-01</b>",
              "rating": "8.1",
              "type": "movie",
              "released": "2008",
              "runtime": "1h51m",
              "largeimage": "http://cdn0.nflximg.net/images/8448/8328448.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt1205489",
              "download": "0"
          },
          {
              "netflixid": "81062606",
              "title": "III Smoking Barrels",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAR9EdxT_uIGgF7FDlc_aekP0qrv7-amMMM91dQwDZtmeVTXnGCvaC7BANCMopKE8I8WaELokDpMLJWlGkZ2Zq-RAXwm480I.jpg?r=3b8",
              "synopsis": "In three stories set in Northeast India, a child goes on the run, a young adult falls in with the wrong crowd and a desperate man turns to crime.<br><b>New on 2019-06-01</b>",
              "rating": "7.9",
              "type": "movie",
              "released": "2017",
              "runtime": "2h7m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "tt5791986",
              "download": "0"
          },
          {
              "netflixid": "70021642",
              "title": "Batman Begins",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAd09u6G0wrtXPVjgvOFLu3aM1RmgfDzXWtM6fjjmwQh8I1K5p181z8aeimIFAPkGN_ddfQHXYHUhZOrzgEGF8qImIQb9w9E.jpg?r=7e8",
              "synopsis": "Following the murder of his parents, Bruce Wayne trains with a shadowy organization and returns to Gotham City to fight crime under a new guise.<br><b>New on 2019-06-01</b>",
              "rating": "8.2",
              "type": "movie",
              "released": "2005",
              "runtime": "2h20m",
              "largeimage": "http://cdn1.nflximg.net/images/4905/23504905.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0372784",
              "download": "0"
          },
          {
              "netflixid": "60020748",
              "title": "A.I. Artificial Intelligence",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAT8h-84pklIv_JqPSuoCRct4KG3K2cPAVPJ0k1Fx9LCOV69WtQIUASFM3E-vsIwUzLycgacBAf7bdyLa0seDR33V7sSQ1Ew.jpg?r=197",
              "synopsis": "In this dark, contemplative tale from Steven Spielberg, an advanced prototype robot child named David is programmed to show unconditional love.<br><b>New on 2019-06-01</b>",
              "rating": "7.1",
              "type": "movie",
              "released": "2001",
              "runtime": "2h25m",
              "largeimage": "http://cdn1.nflximg.net/images/2025/12032025.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0212720",
              "download": "0"
          },
          {
              "netflixid": "81092766",
              "title": "#Selfie 69",
              "image": "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABRVqGHHRriRShZ3NtCqvzxwuJ-T3Uq2kT-WsqC0GBUVfbHZsXfUYLYWimWoXK9zLWDH_7Xa38KH-OKG-8O9UO0ExJq9Sig4.jpg?r=171",
              "synopsis": "After a painful breakup, a trio of party-loving friends makes a bet: who can get married in three days.<br><b>New on 2019-06-01</b>",
              "rating": "0",
              "type": "movie",
              "released": "2016",
              "runtime": "1h58m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "70202141",
              "title": "50/50",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAARawYG4Qj02YHM2ShWkbpsOyjSgEMbA41w3ShcwE06rKfpzH5jKYLVv00N7UERvy9Y10VpEEiLOisIT0FGleLi5l1xIlMQ0.jpg?r=b5c",
              "synopsis": "An otherwise healthy twentysomething has a comically early midlife crisis when he gets slapped with a cancer diagnosis and a 50-50 chance of survival.<br><b>New on 2019-06-01</b>",
              "rating": "7.7",
              "type": "movie",
              "released": "2011",
              "runtime": "1h39m",
              "largeimage": "http://cdn0.nflximg.net/images/7982/21727982.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt1306980",
              "download": "0"
          },
          {
              "netflixid": "70046968",
              "title": "Cat on a Hot Tin Roof",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAfmR0q4eRlYusPW3NeOrEQgMqzBq9mVQ9vbPuWyvD_lbXCC-Fd39IZSKvUVtXSHyKLg7rux8MTYNiM1PskgAa9j2wKwxT5Y.jpg?r=966",
              "synopsis": "Members of a Southern clan scramble to curry favor with a dying, wealthy patriarch in this adaptation of Tennessee Williams&#39;s sizzling stage drama.<br><b>New on 2019-06-01</b>",
              "rating": "8.1",
              "type": "movie",
              "released": "1958",
              "runtime": "1h48m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0051459",
              "download": "0"
          },
          {
              "netflixid": "70038131",
              "title": "Good Night, and Good Luck",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAQDjk8EfdKidW__QM51vb-kvTTgmzWVlUNx5syDfuLG4-y6VfglsRWgis_oUiJ3VvVf9UR7eCjErDvdkfgAs6QSagCeXvA4.jpg?r=4c3",
              "synopsis": "Veteran television newsman Edward R. Murrow faces off against Sen. Joseph McCarthy and his crusade to quell the threat of communism in America.<br><b>New on 2019-06-01</b>",
              "rating": "7.5",
              "type": "movie",
              "released": "2005",
              "runtime": "1h29m",
              "largeimage": "http://cdn0.nflximg.net/images/8302/12118302.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0433383",
              "download": "0"
          },
          {
              "netflixid": "81092768",
              "title": "#Selfie",
              "image": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAdxgCi25nQaNAlLKt8ri9qN79Etqs2PCGLshnOdx0Cdb3peU8zRM8iARW0COSpZMVFrXutW_GjiGhzpY7Nga3ke32hUMWeM.jpg?r=c21",
              "synopsis": "Two days before their final exams, three teen girls make a seaside getaway to end their adolescence with a bang.<br><b>New on 2019-06-01</b>",
              "rating": "",
              "type": "movie",
              "released": "2014",
              "runtime": "2h5m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "352989",
              "title": "Carrie",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAXZJ4TF8eAnriDFvkBlOU_3fpMzz67D9EPy5cKsE2c7kzXvZFzm_E17u0uoex8DjDqiZAra1bgmxc0ujsP2cq8qm2vMJPbM.jpg?r=6d0",
              "synopsis": "An outcast teen with telekinetic ability lashes out with her deadly power when the high school &#39;in crowd&#39; torments her with a sick joke at the prom.<br><b>New on 2019-06-01</b>",
              "rating": "7.4",
              "type": "movie",
              "released": "1976",
              "runtime": "1h38m",
              "largeimage": "http://cdn1.nflximg.net/images/1655/9401655.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0074285",
              "download": "0"
          },
          {
              "netflixid": "342645",
              "title": "Cabaret",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAXoorNQomCoHSojE8u-8Z-CVj9LmtNzAKWigYQXHSNy4iUWIjenR_5yaNH18f_edv2KHjqVdp-DdZ-Dt03xJ4JLaUff8ANQ.jpg?r=ba6",
              "synopsis": "A British scribe and his comrades -- including flamboyant American entertainer Sally Bowles -- chronicle debauchery and turbulence in prewar Berlin.<br><b>New on 2019-06-01</b>",
              "rating": "7.8",
              "type": "movie",
              "released": "1972",
              "runtime": "2h3m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0068327",
              "download": "0"
          },
          {
              "netflixid": "70079583",
              "title": "The Dark Knight",
              "image": "https://occ-0-2433-2705.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAadnpBP-i2aXZ_PhHQgysdRt0Bie_WYlbymsoCL9wayZWycvypmuT7sDAfZid2DSWVvC16CDG9klzPasOR088rroztRuW78.jpg?r=541",
              "synopsis": "As Batman, Lt. Gordon and the district attorney continue to dismantle Gotham&#39;s criminal underground, a new villain threatens to undo their good work.<br><b>New on 2019-06-01</b>",
              "rating": "9",
              "type": "movie",
              "released": "2008",
              "runtime": "2h32m",
              "largeimage": "http://cdn1.nflximg.net/images/2133/8282133.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0468569",
              "download": "0"
          },
          {
              "netflixid": "60026155",
              "title": "What a Girl Wants",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAaVKZ6NyaPecJjlqawaD5mQbEu99Q7AyFp117rjmt6AUzOcCzhjGDRa84oJDc4cRAmp3_LiVZatSiLNArshC4VySav7U_Hs.jpg?r=9fb",
              "synopsis": "In search of the father she&#39;s never met, the daughter of a bohemian American woman heads to Europe and finds that her dad is an uptight politician.<br><b>New on 2019-06-01</b>",
              "rating": "5.9",
              "type": "movie",
              "released": "2003",
              "runtime": "1h44m",
              "largeimage": "http://cdn1.nflximg.net/images/1511/8511511.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0286788",
              "download": "0"
          },
          {
              "netflixid": "81070008",
              "title": "Prosecuting Evil: The Extraordinary World of Ben Ferencz",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAW7KZkFMLsEV5pOMMUF7Ya9Fhwlh-D5iu17jy6jLu5j4XaFgyzXUpt5SUCftgRNzqZ6yPoMfNsGnRi3UdcRlK1YA33ZRz4Q.jpg?r=bcd",
              "synopsis": "A gripping profile of Ben Ferencz, the last surviving lead prosecutor at the Nuremberg trials whose lifelong desire for justice altered the rule of law.<br><b>New on 2019-06-01</b>",
              "rating": "",
              "type": "movie",
              "released": "2019",
              "runtime": "1h22m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "70108017",
              "title": "The Box",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAe5MouohIlktYiBghuaCeNFE0iFYCVhO6Sq4dA1E72NBEiS5_4wF83tMxEUZIOXRcZAOuLM-VKx3qlN-5izjwwyVoDzgIEk.jpg?r=d07",
              "synopsis": "A couple must decide whether to push a button that will net them a million dollars but that will also cause the death of a complete stranger.<br><b>New on 2019-06-01</b>",
              "rating": "5.6",
              "type": "movie",
              "released": "2009",
              "runtime": "1h50m",
              "largeimage": "http://cdn1.nflximg.net/images/6476/8096476.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0362478",
              "download": "0"
          },
          {
              "netflixid": "80203143",
              "title": "Then Came You",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAARgnHnFS9YBDCWTGf7ttzaBXRIOxYc9dyajcaW1d6Lh2u8frit-Jv26SjgAJXb69qZxuQGF2uj3IPbnLFquAg3ZX3ybZt4s.jpg?r=b47",
              "synopsis": "A hypochondriac confronts his fear of death when a terminally ill teen girl enlists him to help her complete her bucket list.<br><b>New on 2019-06-01</b>",
              "rating": "",
              "type": "movie",
              "released": "2019",
              "runtime": "1h36m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "81068732",
              "title": "We Are Legends",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABWe26BZtmEkFo12pYSPDwYxfwMX4EUj3Chm6NoZpGCcrXj2XhFZGKEB4V3jhcgx-8mHq3fKgKNKS2B9jpgmqBpCBX_7_2NM.jpg?r=725",
              "synopsis": "Raised in a boxing gym, two orphaned brothers become highly skilled martial artists and must combat threats in the streets and the ring.<br><b>New on 2019-06-01</b>",
              "rating": "",
              "type": "movie",
              "released": "2019",
              "runtime": "1h48m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "80108430",
              "title": "The Duel",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAX1hzmT59VU2k0_IHuDOKGoJI1vs5ZKF8HXSmk2JNJFz94bzSMGcl5OsxXjtRFr40M8eoiSOrurmkSRmImW8qBvXu7bwVOg.jpg?r=e89",
              "synopsis": "In 1866, a Texas Ranger investigates some suspicious deaths in a town ruled by a religious despot whose past contains a disturbing link to his own.<br><b>New on 2019-06-01</b>",
              "rating": "5.8",
              "type": "movie",
              "released": "2016",
              "runtime": "1h49m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "tt2436682",
              "download": "0"
          },
          {
              "netflixid": "70129179",
              "title": "Straw Dogs",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAR9EN9GPrNeBegRPgDOyaS8BIIRoOKKa5FPeCYsT1-xJknfTAL1I91Yv81IcgPZ4slQ0Q6aax2yQm1vmDnK-jz9lpnJkl50.jpg?r=108",
              "synopsis": "David relocates with his wife, Amy, to her Mississippi hometown, but as detachment strains their marriage, bigger threats loom in their small town.<br><b>New on 2019-06-01</b>",
              "rating": "5.8",
              "type": "movie",
              "released": "2011",
              "runtime": "1h49m",
              "largeimage": "http://cdn1.nflximg.net/images/9866/8579866.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0999913",
              "download": "1"
          },
          {
              "netflixid": "20129240",
              "title": "Small Soldiers",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABXR4tsyRw9UgZY1DyyKj6ssG46VJ9Tx3CyE3a9VM-FeXrYCLg4DUM_dPaixJmFdOC3WhTSdrHuaniK3-RzwuB3RbnijHjA4.jpg?r=b3d",
              "synopsis": "When the Commando Elite, a group of toy action figures, are released before they&#39;ve been tested, they attack the children playing with them.<br><b>New on 2019-06-01</b>",
              "rating": "6.1",
              "type": "movie",
              "released": "1998",
              "runtime": "1h49m",
              "largeimage": "http://cdn0.nflximg.net/images/2742/12072742.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0122718",
              "download": "0"
          },
          {
              "netflixid": "70011219",
              "title": "The Phantom of the Opera: Special Edition",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABa7dgOS6fBkxisVlcNKeU4EC0xFbNh87W7dfCx5jW3_Wfa_NU235yxO7l3hEQdG5cJFCvaaMmAdUa40oinw_Ae1WX4ZXmi4.jpg?r=d46",
              "synopsis": "This big-screen adaptation of the legendary musical stars Gerard Butler as the disfigured, reclusive Phantom who roams beneath the Paris Opera.<br><b>New on 2019-06-01</b>",
              "rating": "7.3",
              "type": "movie",
              "released": "2004",
              "runtime": "2h15m",
              "largeimage": "http://cdn0.nflximg.net/images/0386/12140386.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0293508",
              "download": ""
          },
          {
              "netflixid": "70098605",
              "title": "Righteous Kill",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABTVgg8wKNU169r2kohWGQVRRkfhnrMT5kOAtzQn0SsCS8pN4UGRPo6_XX9F1TusImYgG6niuyQKLZ1GS7WOXsxEySptK4V8.jpg?r=6da",
              "synopsis": "Two detectives investigate a rash of vigilante killings linked to an old case, suggesting they might have put an innocent man behind bars.<br><b>New on 2019-06-01</b>",
              "rating": "6",
              "type": "movie",
              "released": "2008",
              "runtime": "1h40m",
              "largeimage": "http://cdn1.nflximg.net/images/3613/8343613.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt1034331",
              "download": "1"
          },
          {
              "netflixid": "81077539",
              "title": "Satan and Adam",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAASP8WlGrVzgGTbuKPBoT3M_sF2S3VrOsmeZIeWYfdvbICpyfHgTxQIxQemnpHJ-qko1ZA1RXjJhC231m55EviV8VcExFHtw.jpg?r=db7",
              "synopsis": "An aging blues guitarist and a grad student form an unlikely duo while busking on the street corners of 1980s Harlem.<br><b>New on 2019-06-01</b>",
              "rating": "",
              "type": "movie",
              "released": "2018",
              "runtime": "1h17m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "80097424",
              "title": "The Space Between Us",
              "image": "https://occ-0-2433-2705.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAXYR1JqRynlAVMwzEVChiFpb1JiSh6v_qblFSSjBV6ub9L185pwdbVEG1PYuLA8xSNvbTiLb85SX-OvZ6MwRk7pvBh-NKVM.jpg?r=4cb",
              "synopsis": "After years of limited contact with Earth, an inquisitive teen who lives on Mars makes an interplanetary trek to discover his own origins.<br><b>New on 2019-06-01</b>",
              "rating": "6.4",
              "type": "movie",
              "released": "2016",
              "runtime": "2h0m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "tt3922818",
              "download": "0"
          },
          {
              "netflixid": "80196657",
              "title": "March Comes in Like a Lion",
              "image": "https://occ-0-2433-2705.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABbKmAA0vain-JLpTN67Du_FrDWJ2KYW3zqX1p_m9gWlJmyMJ6Xd766JyPNqtyBynUDwkx9cGxtRnKxF7HiG5bziUOMrGiFc.jpg?r=7e9",
              "synopsis": "Orphaned young, a reclusive 17-year-old professional shogi player starts to come out of his shell when three sisters take him under their wing.<br><b>New on 2019-06-01</b>",
              "rating": "8.3",
              "type": "series",
              "released": "2016",
              "runtime": "",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "tt6074794",
              "download": "0"
          },
          {
              "netflixid": "80202183",
              "title": "Herrens veje",
              "image": "https://occ-0-3377-185.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABdjeQvMIpIQ6nClFIndREpYGGmGXipw7jJe1NbLzJ5Xz5thIRYYBGbdx7bwwWG2xIh8ssWZ3y0DH09cRMHDgwHm2O3S77Es.jpg?r=33b",
              "synopsis": "A family with a storied history of service to the Church of Denmark fractures under the tyrannical rule and ambition of its hard-driving patriarch.<br><b>New on 2019-06-01</b>",
              "rating": "",
              "type": "series",
              "released": "2018",
              "runtime": "",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "81028895",
              "title": "Arthdal Chronicles",
              "image": "https://occ-0-64-58.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABSkgAdwhkctzpFqbuSA7KCwT6VKQrmyj6jLhNX1de93vk_6cw-dc01ziMdNWgXPFv02K9W10Ei9K_viYWuRd3UccWzJQ5ZLsTnhp8zdPI-vxAZE2suJqMHe71Ov6j31Pg3bIg-MlEZXpYFOLtaNyn2kfzmKj_A.jpg?r=4c1",
              "synopsis": "In a mythical land called Arth, the inhabitants of the ancient city of Arthdal and its surrounding regions vie for power as they build a new society.<br><b>New on 2019-06-01</b>",
              "rating": "",
              "type": "series",
              "released": "2019",
              "runtime": "",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "81034775",
              "title": "Falsa identidad",
              "image": "https://occ-0-3377-185.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABeItAlXxBOhE_3oFJoAfMLYRpcWd_h6FuqJ1h1h9tpxO3KTtnYHqQEFluCFkH9Pn4GPG8lRb2f2Xjjt2XAWkiP8XOKRhXEo.jpg?r=13a",
              "synopsis": "Strangers Diego and Isabel flee their home in Mexico and pretend to be a married couple to escape his drug-dealing enemies and her abusive husband.<br><b>New on 2019-06-01</b>",
              "rating": "8.4",
              "type": "series",
              "released": "2018",
              "runtime": "",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "tt8598690",
              "download": "0"
          },
          {
              "netflixid": "70228101",
              "title": "Magic Mike",
              "image": "https://occ-0-64-58.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABd-wz_a4TmeQgnvSTnJewXNaGE9_WehQAMfJ-qN2gw9Vd_aIEfj0PaNXCARW9Rt6Bj3EKYbjruw1P5sl7PrUHyTsjYjAaHI.jpg?r=310",
              "synopsis": "Veteran male stripper Magic Mike introduces a new dancer known as the Kid to the pleasures -- and perils -- of their profession.<br><b>New on 2019-06-01</b>",
              "rating": "6.1",
              "type": "movie",
              "released": "2012",
              "runtime": "1h50m",
              "largeimage": "http://cdn0.nflximg.net/images/0523/24140523.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt1915581",
              "download": "1"
          },
          {
              "netflixid": "70099116",
              "title": "Madagascar: Escape 2 Africa",
              "image": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAASXa9jHUMtJpNW11Y2FXLeeWM-ceIA-fT70bLjoFIk-uZxZUOJxWrU950fosCctSzFzROrclqjufvJBlC8bbiITTLTh00zw.jpg?r=e9a",
              "synopsis": "A botched rescue strands Alex the lion and his companions in Africa. Sadly, Alex discovers he has little in common with the locals.<br><b>New on 2019-06-01</b>",
              "rating": "6.7",
              "type": "movie",
              "released": "2008",
              "runtime": "1h29m",
              "largeimage": "http://cdn0.nflximg.net/images/7120/24367120.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0479952",
              "download": "0"
          },
          {
              "netflixid": "81077795",
              "title": "Life in the Doghouse",
              "image": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAYMEytf1CA_FDfwLTCmmALfQ-s-MxE3MPhJodXfUQtnGJt28XoTcPin1KY8zQqNL5Pwey04bPyfrcvj63MA82Z-I6sYbN9E.jpg?r=052",
              "synopsis": "A couple operates a bustling dog rescue out of their own home, vowing to give a safe space to the neediest pups on the planet -- 10,000 and counting.<br><b>New on 2019-06-01</b>",
              "rating": "8.2",
              "type": "movie",
              "released": "2018",
              "runtime": "1h23m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "tt5178264",
              "download": "0"
          },
          {
              "netflixid": "81092767",
              "title": "Love Is a Story",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABUgTlqKuB5E04trZdmbbtj4XS5N-iC-QAzzABmtfEb0N5jxhZ1seqtkjb0UCzu4Wrs0Qcc2tI-7ZCjZK7_Fbr2tJwFoyqn4.jpg?r=e91",
              "synopsis": "Two young artists, a violin player and an actress, fight to achieve their dreams and keep their relationship together during Christmastime.<br><b>New on 2019-06-01</b>",
              "rating": "0",
              "type": "movie",
              "released": "2015",
              "runtime": "1h45m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "tt3764686",
              "download": "0"
          },
          {
              "netflixid": "81110386",
              "title": "Krutant",
              "image": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAboeXb4AV37toCH7Et9trPzrcZqRhk0yvm9WmmEJj15B4c8bnBm3UyrMhaLtGFVjJuVxhIjKG9Dr_StfsYFoJR25-f4gJ2E.jpg?r=023",
              "synopsis": "When a busy workaholic leaves town to meet friends, an unexpected delay leads him to the hut of an old man, whose haunting tale could change his life.<br><b>New on 2019-06-01</b>",
              "rating": "",
              "type": "movie",
              "released": "2019",
              "runtime": "1h53m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "70044752",
              "title": "Network",
              "image": "http://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABZc5Vh3nBz8XDLvCHGui_H2oBk83BHpE-fqrS_KJVvRiGi4ziFz8Fmpbv0jMLvsakJsSwMIjXa2_1kJsRyVDl3t2kFuI1Tw.jpg?r=e29",
              "synopsis": "When a news anchor loses his mind on the air, his outrageous rants boost ratings and intrigue network executives in this Oscar-winning masterpiece.<br><b>New on 2019-06-01</b>",
              "rating": "8.1",
              "type": "movie",
              "released": "1976",
              "runtime": "2h1m",
              "largeimage": "http://cdn1.nflximg.net/images/8603/8768603.jpg",
              "unogsdate": "2019-06-01",
              "imdbid": "tt0074958",
              "download": "0"
          },
          {
              "netflixid": "81092909",
              "title": "Oh, Ramona!",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABQZo50L5rhHlrwoP06jV7tHebtNwn3tWICQPWLRdgHX2yWS9RmOmndmcc2XluO6d7ISVIo5aumevD1nCr_C2E6fKYeOAe7tAuMS8MXt-y6PNR8pDGQ.jpg?r=974",
              "synopsis": "Awkward 16-year-old Andrei is infatuated with his alluring but aloof schoolmate Ramona -- until he meets stunning hotel clerk Anemona while on vacation.<br><b>New on 2019-06-01</b>",
              "rating": "6.3",
              "type": "movie",
              "released": "2019",
              "runtime": "1h49m",
              "largeimage": "",
              "unogsdate": "2019-06-01",
              "imdbid": "tt7200946",
              "download": "0"
          },
          {
              "netflixid": "80244783",
              "title": "Malibu Rescue: The Series",
              "image": "https://occ-0-64-58.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABR7yubPogkm7gSonAAmufe6jruBV1pk7_5VXuwZziDih5BftojfUxIL7nFVOfBYmzs1ggvzfkir1sS86n2zfzZZN-k2SR-EiK1QzbHho-QC_kc0l8Q.jpg?r=f2d",
              "synopsis": "On the heels of Junior Rescue training, Team Flounder returns to brave the beach in a series of thrilling saves and lighthearted laughs.<br><b>New on 2019-06-03</b>",
              "rating": "",
              "type": "series",
              "released": "2019",
              "runtime": "",
              "largeimage": "",
              "unogsdate": "2019-06-03",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "70117293",
              "title": "The Men Who Stare at Goats",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAARCVAH9ZKHZoTIKP5u61mhqk8G1Ktg7E48PDF5C5eDyz9c7UmepYpFGNW8Q2BqvaG5X26yyx-POB_ANBtri39Dupq_dzkyE.jpg?r=8d3",
              "synopsis": "A journalist latches onto an unbelievable story in Iraq when he meets Lyn, a man of mysterious origins who reveals he was a &#39;warrior monk.&#39;<br><b>New on 2019-06-04</b>",
              "rating": "6.2",
              "type": "movie",
              "released": "2009",
              "runtime": "1h33m",
              "largeimage": "http://cdn1.nflximg.net/images/3131/9943131.jpg",
              "unogsdate": "2019-06-04",
              "imdbid": "tt1234548",
              "download": "1"
          },
          {
              "netflixid": "70295178",
              "title": "The Woman in Black 2: Angel of Death",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAASIuJzknpc_qTPxFMmRb6m2u6VRpGpCULACPId6Doy72efmc3sLXXXL8iPRPheBVeGdq5-_ye23-qlCEao33o-hpv6oVoTg.jpg?r=1a8",
              "synopsis": "During World War II, a group of London schoolchildren are evacuated to a dilapidated house, where they unwittingly reawaken a vicious spirit.<br><b>New on 2019-06-05</b>",
              "rating": "4.9",
              "type": "movie",
              "released": "2014",
              "runtime": "1h38m",
              "largeimage": "http://cdn1.nflximg.net/images/9731/20979731.jpg",
              "unogsdate": "2019-06-05",
              "imdbid": "tt2339741",
              "download": "0"
          },
          {
              "netflixid": "70181716",
              "title": "Jiro Dreams of Sushi",
              "image": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAYF0EX5cSKQIlVSmA7JYMnQ3IZiS-6uitKAaucso0UHqjvrJTv7rnNFuaIAVFXOrUS5vBqsnn7cFD2FRJrDbDOgw-qaO0XY.jpg?r=b55",
              "synopsis": "This documentary profiles sushi chef Jiro Ono, an 85-year-old master whose 10-seat, $300-a-plate restaurant is legendary among Tokyo foodies.<br><b>New on 2019-06-05</b>",
              "rating": "7.9",
              "type": "movie",
              "released": "2011",
              "runtime": "1h19m",
              "largeimage": "http://cdn0.nflximg.net/images/7582/23367582.jpg",
              "unogsdate": "2019-06-05",
              "imdbid": "tt1772925",
              "download": "1"
          },
          {
              "netflixid": "80223226",
              "title": "A Silent Voice",
              "image": "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABRvLb_BOZgHH6PtWmiVW6oGg_dF0zsyw3CzXcRH9SPpvv1ONpF7N2Els1WNXo-ZfsJlVG5y7eY9D5CAu1VeM62_5JYIoMcE.jpg?r=22b",
              "synopsis": "A former class bully reaches out to the deaf girl he&#39;d tormented in grade school. He feels unworthy of redemption but tries to make things right.<br><b>New on 2019-06-05</b>",
              "rating": "8.2",
              "type": "movie",
              "released": "2016",
              "runtime": "2h9m",
              "largeimage": "",
              "unogsdate": "2019-06-05",
              "imdbid": "tt5323662",
              "download": "0"
          },
          {
              "netflixid": "70294793",
              "title": "A Perfect Man",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAARfPwJmSXiAmtKtn-59FzItms0doy4SfUkF8shxhcZlr5k-l6tcUuwMPSdAxXk5p-ZcbPMxOG8X2nk9VpIL_oeOCHp9FAUI.jpg?r=d5e",
              "synopsis": "Nina thinks her husband, James, is cheating on her, and she sets out to prove it by calling him and pretending to be another woman.<br><b>New on 2019-06-05</b>",
              "rating": "5.2",
              "type": "movie",
              "released": "2013",
              "runtime": "1h34m",
              "largeimage": "http://cdn0.nflximg.net/images/5523/8865523.jpg",
              "unogsdate": "2019-06-05",
              "imdbid": "tt2275471",
              "download": "1"
          },
          {
              "netflixid": "80079473",
              "title": "Cabin Fever",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAbl4fVDrvLq1vqgek3MXH3_1wtG_QUMV9BJ8fI_3Rka35e2Rl8Rx_vdpzUl1ejMw3tMyReQEqPXOh4DxenRhkLEjSFcwVXU.jpg?r=ecc",
              "synopsis": "As a flesh-eating virus rips its way through a remote woodland cabin, the terrified teens vacationing inside wonder who&#39;ll fall victim next.<br><b>New on 2019-06-05</b>",
              "rating": "3.7",
              "type": "movie",
              "released": "2016",
              "runtime": "1h38m",
              "largeimage": "",
              "unogsdate": "2019-06-05",
              "imdbid": "tt3832096",
              "download": "1"
          },
          {
              "netflixid": "80039136",
              "title": "Immoral Tales",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAWzCgbSp4YiyqoF0cXKmxYCDQJ0vxiKQD7XIgrPutunK29GwGYPKbAyrPuUqRfhIdj3uMXRRDzdMh1DRpLcgnEUD5-WmEVI.jpg?r=960",
              "synopsis": "This anthology illustrates the timeless nature of desire in four stories of incest, bloodlust and other forbidden subjects.<br><b>New on 2019-06-05</b>",
              "rating": "5.7",
              "type": "movie",
              "released": "1974",
              "runtime": "1h43m",
              "largeimage": "http://cdn0.nflximg.net/images/4556/22544556.jpg",
              "unogsdate": "2019-06-05",
              "imdbid": "tt0071359",
              "download": "1"
          },
          {
              "netflixid": "80996790",
              "title": "Dr. Seuss&#39; The Grinch",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAb2SnszEF7daHRlsJZwzAkedFQgLcQqnK9AgDmEobMH1TcgG4Z8-pK261j3LWr-cliJJIj8YnXsYUbikDqOjQhl8FMcfVkU.jpg?r=114",
              "synopsis": "A grump with a mean streak plots to bring Christmas to a halt in the cheerful town of Whoville. But a generous little girl could change his heart.<br><b>New on 2019-06-05</b>",
              "rating": "",
              "type": "movie",
              "released": "2018",
              "runtime": "1h25m",
              "largeimage": "",
              "unogsdate": "2019-06-05",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "81076055",
              "title": "Dolphin Kick",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAV2CxXHzNwCCeNRV4UJ4BRu02UaPnvk5_lej4YFaQsi1NfDqGRYi0Xvh1cwzZ7tlmv0meDHhftTQdEUQzix9tkvIpFb_4ZA.jpg?r=9b3",
              "synopsis": "After losing his mom, 10-year-old Luke abandons competitive swimming. It takes a friendly dolphin to get him back in the water -- and help him heal.<br><b>New on 2019-06-05</b>",
              "rating": "6.4",
              "type": "movie",
              "released": "2019",
              "runtime": "1h29m",
              "largeimage": "",
              "unogsdate": "2019-06-05",
              "imdbid": "tt5774054",
              "download": "0"
          },
          {
              "netflixid": "70270388",
              "title": "Would You Rather",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABSGFkZrBeRyh0LXdhBwCBMmWVYRvn7gDdn76Fs9bWIKvWirKMrFGCnnlSB-1hdS43eTCEFc63yWlLB1BwhHCYbJbdpbyH0g.jpg?r=d7b",
              "synopsis": "In need of cash to help her sick brother, a young woman agrees to take part in a lethal winner-takes-all parlor game hosted by a sadistic millionaire.<br><b>New on 2019-06-05</b>",
              "rating": "5.7",
              "type": "movie",
              "released": "2013",
              "runtime": "1h33m",
              "largeimage": "http://cdn0.nflximg.net/images/4126/9114126.jpg",
              "unogsdate": "2019-06-05",
              "imdbid": "tt1999995",
              "download": "1"
          },
          {
              "netflixid": "80018328",
              "title": "Christian Mingle",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAQY-IjCePgjdN6s9oNeW9uqsM7k4oivBxPjYB9RIxRNnlURnNDpi7Hyv8_bS0jaBGsXY7sp09J8DH3k6jOgyX_JgE2Q6ZDU.jpg?r=57e",
              "synopsis": "A career woman who has everything but romance finds her values challenged when she starts dating a good man she met on a Christian matchmaking site.<br><b>New on 2019-06-06</b>",
              "rating": "4.3",
              "type": "movie",
              "released": "2014",
              "runtime": "1h39m",
              "largeimage": "",
              "unogsdate": "2019-06-06",
              "imdbid": "tt3398066",
              "download": "1"
          },
          {
              "netflixid": "81030855",
              "title": "Alles ist gut",
              "image": "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABaNKm7Bunj87bOJzozalYK8yMcci87kwzKtCPIXDScaukMggRVXuIsUcF7kOnarKD8YjFWgi5g3hi2mahG8MawFxHG8xEadOpyc8LVwp13uzDhpW3A.jpg?r=e8e",
              "synopsis": "A woman sexually assaulted by her new boss&#39;s brother-in-law tries to move on as if nothing happened, but the night weighs heavily on her mind and body.<br><b>New on 2019-06-06</b>",
              "rating": "",
              "type": "movie",
              "released": "2019",
              "runtime": "1h30m",
              "largeimage": "",
              "unogsdate": "2019-06-06",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "81035837",
              "title": "From Japan to Egypt",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABTDXKuCzL8Y44mk-yOlNNBqDsj1E8oEyq0V-TV0733Pc0YfANuNgV0Baf58euAfcvZh5WuoSvDFdFmYxZH8SMdOOkE3B8Ms.jpg?r=f58",
              "synopsis": "After his wife relocates to her home country of Japan, an Egyptian man -- and father of two rambunctious kids -- tries to win her back.<br><b>New on 2019-06-06</b>",
              "rating": "",
              "type": "movie",
              "released": "2017",
              "runtime": "1h33m",
              "largeimage": "",
              "unogsdate": "2019-06-06",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "81035881",
              "title": "Farce",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAeeSbLmVBu5iKicEVFjKAbY7fzCDdApR7rYmQZZU3s4UGUiQ45KAzZQwdP3kWB3BjmKy6qh9yG14_Z9eRQP8AEonJeXOmlc.jpg?r=f9e",
              "synopsis": "A beauty expert, a drug dealer and a bungling revolutionary end up in the grips of an extremist group after meeting on a plane to Lebanon.<br><b>New on 2019-06-06</b>",
              "rating": "",
              "type": "movie",
              "released": "2017",
              "runtime": "1h33m",
              "largeimage": "",
              "unogsdate": "2019-06-06",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "80996787",
              "title": "Everybody Knows",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAATslKhl18fA8zm0UerepRAiTCM5nk9I4u0so9xEnFxr3bCCOjvod-TGkCh4sTrJ_yMFUpvEh9TTcaIJwAtiIpA-B2ijOitw.jpg?r=ef4",
              "synopsis": "Journeying back to her small Spanish hometown for her sister&#39;s wedding, Laura must grapple with long-buried secrets when her daughter is abducted.<br><b>New on 2019-06-06</b>",
              "rating": "",
              "type": "movie",
              "released": "2019",
              "runtime": "2h13m",
              "largeimage": "",
              "unogsdate": "2019-06-06",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "81035843",
              "title": "Freezer&#39;s Campaign",
              "image": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAd8arKCVKF0eLwfkzOZ6jBQGJcXK5UJ9sYusCGXCyznf7UWCu3ilMB3zZZTX4LmAhJ9_ETBd-HkcS4fzJ956i3W6vicBm7Y.jpg?r=fda",
              "synopsis": "When climate change makes Egypt freeze over, intelligence officers pose as a film crew on location to seek a device that can eliminate the frost.<br><b>New on 2019-06-06</b>",
              "rating": "",
              "type": "movie",
              "released": "2016",
              "runtime": "1h55m",
              "largeimage": "",
              "unogsdate": "2019-06-06",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "81035884",
              "title": "It&#39;s Okay, Buddy",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAARUkOzeSxlZgWilTkjdEH88bRERUYolNj0v811lg7mXkilj5sndm7kJMCo3vtMwk5q8aKXgZd4em2D-3_Q5ItX1Ow2INPQc.jpg?r=f53",
              "synopsis": "Two down-on-their-luck singers set out to marry wealthy women -- but not everyone is happy to have them climb the social ladder.<br><b>New on 2019-06-06</b>",
              "rating": "",
              "type": "movie",
              "released": "2017",
              "runtime": "1h23m",
              "largeimage": "",
              "unogsdate": "2019-06-06",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "81035852",
              "title": "Best Neighbors",
              "image": "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABfjAXNbQoi056sY7xM5y3b4nUTZVbYHduizLNMLRmJvXDS6SSGTRaV1sxTvgU_O2lGqGooxLJ7N0phoDGNihAIvC8d9n5Ks.jpg?r=023",
              "synopsis": "A just-married couple moves into their new home, finding themselves at war with the kids next door, who seem determined to make their lives miserable.<br><b>New on 2019-06-06</b>",
              "rating": "",
              "type": "movie",
              "released": "2014",
              "runtime": "1h38m",
              "largeimage": "",
              "unogsdate": "2019-06-06",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "81035858",
              "title": "Sameer Abu Alneel",
              "image": "https://occ-0-299-300.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABQJd9kEZ90cqQ7nfrDz8XoXnMRBP1VFzy9seXfUW99Tyo1Z17KrlLA9KO2e3pUnWNuehxtt3d6XgkqnJAmxyxhVmsLbD-Jg.jpg?r=cc4",
              "synopsis": "Disliked for his stinginess, Samir finds his life turned upside down when he receives a windfall and launches a television channel.<br><b>New on 2019-06-06</b>",
              "rating": "",
              "type": "movie",
              "released": "2013",
              "runtime": "1h46m",
              "largeimage": "",
              "unogsdate": "2019-06-06",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "81035882",
              "title": "Step Outside",
              "image": "https://occ-0-3451-3446.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAQyzwLW4J9GQUyUVViYnPlhn-Bc5lHygrNzqwmF-HNMYPEfNuLbrkiKNqNm9uvy62MSjo6BRSOSVzP9vJqAsU_Zm2VlPc1Y.jpg?r=87f",
              "synopsis": "A down-on-his-luck man reads a book, only to have its characters materialize and take over his life.<br><b>New on 2019-06-06</b>",
              "rating": "",
              "type": "movie",
              "released": "2018",
              "runtime": "1h29m",
              "largeimage": "",
              "unogsdate": "2019-06-06",
              "imdbid": "",
              "download": "0"
          },
          {
              "netflixid": "81035847",
              "title": "The Republic of Imbaba",
              "image": "https://occ-0-1223-58.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAAAZb5xE8NKWuOEEQk3xvFvpR2qW9AJzj2XSfvaK56OkiIjNpMtC-vCIzFhegzOcmWpEXd7F0WbHUnFTdpx8rwW8rcmlz4UvY.jpg?r=f9f",
              "synopsis": "Living on the edges of Cairo&rsquo;s Embabah neighborhood, several residents seek to better their circumstances following the January 25 Revolution.<br><b>New on 2019-06-06</b>",
              "rating": "",
              "type": "movie",
              "released": "2015",
              "runtime": "1h30m",
              "largeimage": "",
              "unogsdate": "2019-06-06",
              "imdbid": "",
              "download": "0"
          }
    ].each do |movie|
      puts "Title: #{movie[:title]} ---------"
      unless Movie.find_by(netflix_id: movie[:netflixid])
        Movie.create!(
          netflix_id: movie[:netflixid],
          title: movie[:title],
          image: movie[:image],
          synopsis: movie[:synopsis],
          rating: movie[:rating],
          released: movie[:released],
          runtime: movie[:runtime]
        )
      end
    end
  end
end